export type BrowseRecipe = {name: string, rating: number, link: string, image: string, description: string}
  
  export const BROWSE_RECIPES: BrowseRecipe[] = [
    { name: "Homestyle Macaroni and Cheese", rating: 4.7, link: "https://www.food.com/recipe/homestyle-macaroni-and-cheese-12360", image: "https://www.tastingtable.com/img/gallery/15-pro-tips-from-celebrity-chefs-for-next-level-mac-and-cheese/intro-1764869085.jpg", description: "Creamy, cheesy, hearty. A comfort food perfect for weeknights."},
    { name: "Baja Fish Tacos", rating: 5, link: "https://www.food.com/recipe/fish-tacos-baja-style-286078", image: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_860,ar_3:2/v1/img/recipes/28/60/78/5ex24pRhRyidKhSjs6DY_fish%20tacos%20baja%20SITE-3.jpg", description: "Crispy, double-friend fish - fresh and light!"},
    { name: "Classic Lasagna", rating: 5, link: "https://www.food.com/recipe/classic-lasagna-56153", image: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_iw/v1/img/recipes/56/15/3/Bw0OkeMwTZWIgqOi8Ytx_0S9A9367.jpg", description: "Layered pasta with rich meat sauce and melted mozarella."},
    { name: "Thai Iced Tea", rating: 4.5, link: "https://www.food.com/recipe/thai-iced-tea-33910", image: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_860,ar_3:2/v1/img/recipes/33/91/0/pxLeMNWKRYJpWLFAfPoT_0S9A7337.jpg", description: "Refreshing Thai tea served over ice."},
    { name: "Szechuan Dan Dan Noodles", rating: 4, link: "https://www.food.com/recipe/szechuan-dan-dan-noodles-107773", image: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_iw/v1/img/recipes/10/77/73/Y111q0CCRj6IlFr25QEj_Szechuan%2520dan%2520dan%2520noodles%2520107773-2.jpg", description: "Quick and flavorful. Also has a spicy kick to it!"},
    { name: "Channa Masala", rating: 4.5, link: "https://www.food.com/recipe/channa-masala-17471", image: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_960/v1/img/recipes/17/47/1/gHa9bxe7QJKKYszNosWm_0S9A3962.jpg", description: "A recipe adapted from Madhur Jaffrey's classic."},
    { name: "Spinach Artichoke Dip", rating: 4.9, link: "https://www.food.com/recipe/spinach-artichoke-dip-1209", image: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_960/v1/img/recipes/12/09/nRzlWGFKR3STxeNPYv4C_0S9A2666.jpg", description: "Perfect everywhere - from game nights to picnics!"},
    { name: "Vegan Brownies", rating: 4.2, link: "https://www.food.com/recipe/vegan-brownies-19282", image: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_960/v1/img/recipes/19/28/2/wUx7v3crRau0qno0Fthg_0S9A8552.jpg", description: "Egg-free, sweet, gooey, fudgy, chocolatey, amazing."},
    { name: "Lemonade Scones - Gluten-Free", rating: 4, link: "https://www.food.com/recipe/lemonade-scones-gluten-free-221956", image: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_960/v1/img/recipes/22/19/56/X74FgabSS2udIgXN7gSk_lemonade%20scones%20SITE.jpg", description: "Simple, delightful lemon treats."},
  ]