"""Add unit to RecipeIngredient

Revision ID: 55eb58bf3521
Revises: 8fc52475a623
Create Date: 2026-04-07 16:30:41.645672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55eb58bf3521'
down_revision: Union[str, None] = '8fc52475a623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'unit')
    # ### end Alembic commands ###
