"""add_recipeingredient_table

Revision ID: 8fc52475a623
Revises: 888efe110e20
Create Date: 2026-04-07 18:43:40.596259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fc52475a623'
down_revision: Union[str, None] = '888efe110e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('raw_ingredient', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipes', sa.Column('name', sa.String(), nullable=False))
    op.add_column('recipes', sa.Column('directions', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('recipes', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recipes', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('link', sa.String(), nullable=True))
    op.drop_column('recipes', 'date_submitted')
    op.drop_column('recipes', 'recipe_link')
    op.drop_column('recipes', 'title')
    op.drop_column('recipes', 'instructions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('recipe_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('date_submitted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'link')
    op.drop_column('recipes', 'date')
    op.drop_column('recipes', 'tags')
    op.drop_column('recipes', 'directions')
    op.drop_column('recipes', 'name')
    op.drop_table('recipe_ingredients')
    # ### end Alembic commands ###
